SEARCH_INPUT = "//input[@name='search']"
SEARCH_BUTTON = "//button[contains(@class, 'search-form__submit')]"
CART_ADD_ICON = "(//button[contains(@class, 'buy-button')])[1]"
CART_BUTTON = "//button[contains(@class, 'header-cart__button')]"
MACBOOK = "//span[contains(@class, 'cart-product__title') and contains(text(), 'MacBook Air')]"
SPAN_MACBOOK = "//span[contains(@class, 'goods-tile__title')]"